### ISSUE TITLE
Create Cycle-2 and add deliverables/milestones

### ISSUE THREAD

**Issue by tms-epcc** [wfau/ScienceArchives#444]
- [x] Create the release 
- [x] Move outstanding deliverables/milestones from previous six months into it
- [x] Add to the release the deliverables/milestones due during this six month period
