### ISSUE TITLE
Create cycle-3 plan and add milestones/deliverables

### ISSUE THREAD

**Issue by tms-epcc** [wfau/ScienceArchives#527]
- [x] Create the [release ](https://app.zenhub.com/workspaces/science-archives-project-management-6437c97cbb0b3e891a24bc8c/board?releases=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvMTAxMzk3)
- [x] Move outstanding deliverables/milestones from previous six months into it
- [x] Add to the release the deliverables/milestones due during this six month period
