### ISSUE TITLE
Create cycle-4 plan and add milestones/deliverables

### ISSUE THREAD

**Issue by tms-epcc** [wfau/ScienceArchives#619]
- [x] Create the [release ])
- [x] Move outstanding deliverables/milestones from previous six months into it
- [x] Add to the release the deliverables/milestones due during this six month period
